

### работа с файлами. добавить просмотр всех файлов для admin
GET http://127.0.0.1:8000/api/file/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyMzY2ODk5LCJpYXQiOjE3MjIzNjMyOTksImp0aSI6IjkwMmNhZjhkNDkyYjQ4NDNhZjNjYmQwMjJiNjBiMzc0IiwidXNlcl9pZCI6MX0.fYgxIOIOL3Xz83ljnebuQUVcyZYHExw-EQvDNWyu940	



###
GET http://127.0.0.1:8000/download/None_Screenshot_2.jpg"


###
GET http://127.0.0.1:8000/api/file/18/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyMzY2ODk5LCJpYXQiOjE3MjIzNjMyOTksImp0aSI6IjkwMmNhZjhkNDkyYjQ4NDNhZjNjYmQwMjJiNjBiMzc0IiwidXNlcl9pZCI6MX0.fYgxIOIOL3Xz83ljnebuQUVcyZYHExw-EQvDNWyu940	

GET http://127.0.0.1:8000/api/file/2/download/
Authorization: Bearer 


### Получение списка пользовател
GET http://127.0.0.1:8000/api/ad/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNTg2NDI4LCJpYXQiOjE3MjI1ODI4MjgsImp0aSI6ImUzYTI3MTA2MjY4ZTQ0M2Q4MGRmNGRmNGE3NjhkYzBmIiwidXNlcl9pZCI6MX0.e72M7TtbL_-rbPTmp8tKhGdLYzTKE33gwioWVXn_RIE

###
POST http://127.0.0.1:8000/register/
Content-Type:  application/json

{
    "username": "oleg",
    "email": "testuser@example.com",
    "password": "1234"
}


###
POST  http://127.0.0.1:8000/logout/
Authorization: Token 64fea4167eee65bf02edb98475fd8cb1773ccdd5

###
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "username": "notadmin",
    "password": "00000000"
}

###

GET http://127.0.0.1:8000/api/ad/me/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNTg3MjAyLCJpYXQiOjE3MjI1ODM2MDIsImp0aSI6ImQxZTdjYTZkYTUxYzQwMGY5YzgzMDUyYmZmMzk5ZWYzIiwidXNlcl9pZCI6MX0.XP0q4wwoKJAEUeHy8Kaqi4-XTJmdg8dQXyIyCIV6vLc