

### работа с файлами. добавить просмотр всех файлов для admin
GET http://127.0.0.1:8000/api/download/115/liberty_link/
Content-Type: application/json

###
GET  http://127.0.0.1:8000/api/file/104/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyOTcxNDUxLCJpYXQiOjE3MjI5Njc4NTEsImp0aSI6ImVmMzNlNWMyNjZjYTQ4OGJhYmUzYWZlNzA3MTg5ZmNkIiwidXNlcl9pZCI6MTl9.nAkuBnPHT7g5wPB4YdSR--bNb4wyK7sJNxVayLe8hgo


GET   http://127.0.0.1:8000/api/file/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyOTM2NTQ5LCJpYXQiOjE3MjI5MzI5NDksImp0aSI6ImUxNzNhMjRlN2NhNDQzN2M5YTZiZTlhYTQxNzY3ZmQ0IiwidXNlcl9pZCI6MTh9.C-zEjeg8L7HfTqregruXUrP94GzDDx-vfeMC7J_Bew8


### Получение списка пользовател
GET  http://127.0.0.1:8000/api/ad/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyOTM2NTQ5LCJpYXQiOjE3MjI5MzI5NDksImp0aSI6ImUxNzNhMjRlN2NhNDQzN2M5YTZiZTlhYTQxNzY3ZmQ0IiwidXNlcl9pZCI6MTh9.C-zEjeg8L7HfTqregruXUrP94GzDDx-vfeMC7J_Bew8
