

### работа с файлами. добавить просмотр всех файлов для admin
GET http://127.0.0.1:8000/api/file/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNjk5Mzc4LCJpYXQiOjE3MjI2OTU3NzgsImp0aSI6IjIyY2E1ODYyNmY1MDQ2NmRiNWZhZTQ3ZjUzMzEyZWI0IiwidXNlcl9pZCI6MX0.poFVXeS-TyBEh6YOAN4JEWtk4MvI7cPOZRVJYGmYne4



###
GET http://127.0.0.1:8000/download/None_Screenshot_2.jpg"


###
GET http://127.0.0.1:8000/api/file/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNjk5Mzc4LCJpYXQiOjE3MjI2OTU3NzgsImp0aSI6IjIyY2E1ODYyNmY1MDQ2NmRiNWZhZTQ3ZjUzMzEyZWI0IiwidXNlcl9pZCI6MX0.poFVXeS-TyBEh6YOAN4JEWtk4MvI7cPOZRVJYGmYne4


### Получение списка пользовател
GET  http://127.0.0.1:8000/api/ad/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNzg4NjE0LCJpYXQiOjE3MjI3ODUwMTQsImp0aSI6IjZlNjkzZGVhN2I0MDQ4YjZiMzU0ZDhjZTdjN2VmMjNlIiwidXNlcl9pZCI6MX0.u6MS66zxN2oaRYmNlO4LYPVLILqR3waasJh61dWE__g

###
POST http://127.0.0.1:8000/register/
Content-Type:  application/json

{
    "username": "oleg",
    "email": "testuser@example.com",
    "password": "1234"
}


###
POST  http://127.0.0.1:8000/logout/
Authorization: Token 64fea4167eee65bf02edb98475fd8cb1773ccdd5

###
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "username": "notadmin",
    "password": "00000000"
}

###

PATCH  http://127.0.0.1:8000/api/ad/17/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNzg4NjE0LCJpYXQiOjE3MjI3ODUwMTQsImp0aSI6IjZlNjkzZGVhN2I0MDQ4YjZiMzU0ZDhjZTdjN2VmMjNlIiwidXNlcl9pZCI6MX0.u6MS66zxN2oaRYmNlO4LYPVLILqR3waasJh61dWE__g

{
    "is_superuser": true,
    "is_staff": true
}