# Generated by Django 5.0.7 on 2024-08-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='folder_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='storage_path',
        ),
    ]
