# Generated by Django 5.0.7 on 2024-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_myuser_is_admin_alter_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
