# Generated by Django 5.0.7 on 2024-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='total_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
