# Generated by Django 5.0.7 on 2024-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='urlpath',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='special_url',
            field=models.URLField(blank=True),
        ),
    ]
