# Generated by Django 5.0.7 on 2024-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='namefile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
