# Generated by Django 5.0.7 on 2024-07-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_comment_alter_file_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(blank=True, default=None),
        ),
    ]
