# Generated by Django 5.0.7 on 2024-07-12 17:41

import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='namefile',
            new_name='original_name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='last_date_download',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='special_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='file',
            name='unique_name',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='urlpath',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=files.models.user_directory_path),
        ),
    ]
